//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventMapping = new HashSet<EventMapping>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime Date { get; set; }
        public string Location { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public bool Type { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Desciption { get; set; }
        public string Others { get; set; }
        public string Emails { get; set; }
        public string OwnerEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventMapping> EventMapping { get; set; }
    }
}
